### ISSUE TITLE
GraalVM Native Image can't instantiate SocketFactory Class

### ISSUE THREAD

**Issue by ThusSpokeBieu** [kohlschutter/junixsocket#152]
**Describe the bug**
It works perfectly running as a JAR, but when I create a native image with graalVM trying to connect to postgres with PGSimpleDataSource it will returns the error: "The SocketFactory class provided org.newsclub.net.unix.AFUNIXSocketFactory$FactoryArg could not be instantiated."

I have tried to make connections in other ways, such as with connection string but still no success. I also added the META-INF, generated in the native-graalvm as indicated, you can see the configuration and the repository here: https://github.com/ThusSpokeBieu/rinha-crebito-activej/tree/main/src/main/resources/META-INF/native-image/github.mess/activej-crebito (yeah, it's the repository that i am trying to build)

**To Reproduce**
1. Try to build a PGSimpleDataSource with the socketFactory: “org.newsclub.net.unix.AFUNIXSocketFactory$FactoryArg”
2. Try to compile to native and run the generated binary.

```java
Connection dataSourcePg() throws SQLException, IOException {
    PGSimpleDataSource dataSource = new PGSimpleDataSource();
    dataSource.setDatabaseName("database");
    dataSource.setUser("user");
    dataSource.setPassword("password");
    dataSource.setSocketFactory("org.newsclub.net.unix.AFUNIXSocketFactory$FactoryArg");
    dataSource.setSocketFactoryArg("/var/run/postgresql/.s.PGSQL.5432");

    return dataSource.getConnection();
  }
```

**Expected behavior**
The program should run as a GraalVM native-image as well as a .JAR file.

**Output/Screenshots**
This is the stacktrace I get when I try to run the image:

```bash
Caused by: org.postgresql.util.PSQLException: The SocketFactory class provided org.newsclub.net.unix.AFUNIXSocketFactory$FactoryArg could not be instantiated.
        at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:43)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:227)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
        at org.postgresql.Driver.makeConnection(Driver.java:444)
        at org.postgresql.Driver.connect(Driver.java:297)
        at java.sql@21.0.2/java.sql.DriverManager.getConnection(DriverManager.java:683)
        at java.sql@21.0.2/java.sql.DriverManager.getConnection(DriverManager.java:230)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
        at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:87)
        at github.mess.App.dataSourcePg(App.java:56)
        at java.base@21.0.2/java.lang.reflect.Method.invoke(Method.java:580)
        at io.activej.inject.util.ReflectionUtils.lambda$bindingFromMethod$9(ReflectionUtils.java:340)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: org.newsclub.net.unix.AFUNIXSocketFactory$FactoryArg
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:122)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:86)
        at java.base@21.0.2/java.lang.Class.forName(DynamicHub.java:1356)
        at java.base@21.0.2/java.lang.Class.forName(DynamicHub.java:1319)
        at java.base@21.0.2/java.lang.Class.forName(DynamicHub.java:1312)
        at org.postgresql.util.ObjectFactory.instantiate(ObjectFactory.java:50)
        at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:39)
        ... 18 more
```

**Notes**
Maybe I am missing something, please forgive me if that is the case. I am open to other solutions for the connection if possible.

Thank you

**Comment by kohlschuetter** [comment]
Thanks for reporting, @ThusSpokeBieu !

I believe this is due to some missing META-INF/native-image configuration. Working on it.

**Comment by kohlschuetter** [comment]
@ThusSpokeBieu Please try the latest 2.9.1-SNAPSHOT version.

Alternatively, try adding the latest version of the file [`/META-INF/native-image/com.kohlschutter.junixsocket/junixsocket-common/reflect-config.json`](https://github.com/kohlschutter/junixsocket/blob/main/junixsocket-common/src/main/resources/META-INF/native-image/com.kohlschutter.junixsocket/junixsocket-common/reflect-config.json) to your project's resource classpath.

**Comment by ThusSpokeBieu** [comment]
It worked perfectly, thank you!

**Comment by czp3009** [comment]
I know this issue is closed, but I think my question is related to this issue, so I'll comment here.

I'm having a similar problem, but I'm using the CJ style SocketFactory

```
Caused by: java.lang.ClassNotFoundException: org.newsclub.net.mysql.AFUNIXDatabaseSocketFactoryCJ
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:123) ~[na:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:87) ~[na:na]
        at java.base@17.0.10/java.lang.Class.forName(DynamicHub.java:1322) ~[identity-service:na]
        at java.base@17.0.10/java.lang.Class.forName(DynamicHub.java:1311) ~[identity-service:na]
        at com.mysql.cj.util.Util.getInstance(Util.java:187) ~[na:na]
        ... 142 common frames omitted
```
i read the source code of version 2.9.1-SNAPSHOT mentioned above, i think should also add native hints for CJ style SocketFactory
