### ISSUE TITLE
Request a tutorial

### ISSUE THREAD

**Issue by Hesam-Naderi-Dehkordi** [kohlschutter/junixsocket#18]
Hi there. I was searching a good tutorial on how to use your library, but didn't find anything.
I'm new to JNI and don't know how to use your library.
I have .jar files of your library but when trying to import and use them I get some errors like this :
Exception in thread "main" java.lang.NoClassDefFoundError: org/scijava/nativelib/JniExtractor
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
    at org.newsclub.net.unix.AFUNIXServerSocket.<init>(AFUNIXServerSocket.java:51)
    at org.newsclub.net.unix.AFUNIXServerSocket.newInstance(AFUNIXServerSocket.java:63)
    at org.newsclub.net.unix.demo.SimpleTestServer.main(SimpleTestServer.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.ClassNotFoundException: org.scijava.nativelib.JniExtractor
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 11 more

Process finished with exit code 1

**Comment by kohlschuetter** [comment]
We're getting rid of JniExtractor in 2.1.
Also there's now better documentation on https://kohlschutter.github.io/junixsocket/

**Comment by shubham643** [comment]
Hi kohlschuetter,
I am also facing this exactly same error. Can you please let me know about how to resolve this?

**Comment by shubham643** [comment]
Is it that 2.1.2 is not using any native library? I somehow fixed jniextractor issue but got stuck at connectto method in NativeUnixSocket class

**Comment by kohlschuetter** [comment]
junixsocket 2.1 no longer uses JniExtractor to load the native library. We now have a custom native library loader.
