### ISSUE TITLE
UnsatisfiedLinkError thrown sometimes when AFUNIXSocket initialised concurrently

### ISSUE THREAD

**Issue by nhoughto** [kohlschutter/junixsocket#45]
We are experiencing non-deterministic failures when using this library via `docker-java` via `gradle-docker-plugin`.

Our workflow is currently to use a Gradle task to build a number of images (currently 25) in parallel `gradle --parallel ...`, the Gradle plugin uses `docker-java` library which uses this library to communicate with the docker host via the docker socket `/var/run/docker.sock`. When run in serial no error is thrown, but when in run parallel sometimes a race condition is hit where it appears the native library binary cannot be loaded by the JVM and an error like the below is shown:

```
Caused by: java.lang.ExceptionInInitializerError
    at org.newsclub.net.unix.AFUNIXSocket.<init>(AFUNIXSocket.java:36)
    at org.newsclub.net.unix.AFUNIXSocket.newInstance(AFUNIXSocket.java:54)
    at com.github.dockerjava.jaxrs.ApacheUnixSocket.<init>(ApacheUnixSocket.java:51)
    at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.createSocket(UnixConnectionSocketFactory.java:66)
    at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:118)
    at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
    at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
    at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
    at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
    at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
    at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
    at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
    at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
    at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
    at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
    at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
    at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
    at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
    at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
    at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:42)
    ... 26 more
Caused by: java.lang.reflect.InvocationTargetException
    at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
    ... 26 more
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libjunixsocket-native-2.0.42131647397275370483.so: Error loading shared library /tmp/libjunixsocket-native-2.0.42131647397275370483.so: No such file or directory
    at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:39)
    ... 27 more
```

The same behaviour is found on Mac and Linux (local vs CI). Looking through the code my assumption is that it is a race condition with the way the native library is loaded, as the native libraries are read from the JAR and then written to a temp file before being loaded, this potentially doesn't play well with the way AFUNIXSocket and the NativeUnixSocket singleton interact when being run in parallel. Specifically the `NativeUnixSocket.setCreated()` static native method wrapper in AFUNIXSocket constructor.

Our two current workarounds for this problem are to serialise our image builds rather than do them in parallel (unacceptable as it takes too long), or to use `DOCKER_HOST` to have the `docker-java` use the `tcp://...` rather than AFUNIXSocket, which doesn't work well on mac and requires a `socat` tcp->socket proxy. I realise this library is mostly~ unmaintained, hasn't been updated in a while so this is mostly here for the next person who is googling around with the same problem. 👍

**Comment by kohlschuetter** [comment]
This should be fixed in 2.1.0. Please verify. Thanks for reporting!
