### ISSUE TITLE
Not supported on Raspberry Pi (2.0.4)

### ISSUE THREAD

**Issue by nikoshet** [kohlschutter/junixsocket#50]
Hello,
i am trying to use the junixsocket with maven on Raspberry Pi 3 (as well as on Docker container on RPi) but the following error persists after hours of trying to find a solution:
```
java.lang.RuntimeException: Library 'libjunixsocket-native-2.0.4.so' not found!
	at org.newsclub.net.unix.NarSystem.getLibPath(NarSystem.java:132)
	at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
	at org.newsclub.net.unix.AFUNIXServerSocket.<init>(AFUNIXServerSocket.java:51)
	at org.newsclub.net.unix.AFUNIXServerSocket.newInstance(AFUNIXServerSocket.java:63)
	at Server.main(Server.java:16)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.newsclub.net.unix.AFUNIXServerSocket.<init>(AFUNIXServerSocket.java:51)
	at org.newsclub.net.unix.AFUNIXServerSocket.newInstance(AFUNIXServerSocket.java:63)
	at Server.main(Server.java:16)
Caused by: java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException
	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:42)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.newsclub.net.unix.NativeUnixSocket.<clinit>(NativeUnixSocket.java:35)
	... 3 more
Caused by: java.lang.RuntimeException: Library 'libjunixsocket-native-2.0.4.so' not found!
	at org.newsclub.net.unix.NarSystem.getLibPath(NarSystem.java:132)
	at org.newsclub.net.unix.NarSystem.loadLibrary(NarSystem.java:36)
	... 8 more
```
The dependencies on pom.xml are:
```
        <dependency>
            <groupId>com.kohlschutter.junixsocket</groupId>
            <artifactId>junixsocket-common</artifactId>
            <version>2.0.4</version>
        </dependency>
        <dependency>
            <groupId>com.kohlschutter.junixsocket</groupId>
            <artifactId>junixsocket-native-common</artifactId>
            <version>2.0.4</version>
        </dependency>
```
Is there a chance to have it support Raspberry Pi? Has anyone achieved it?
Thanks in advance.

**Comment by kohlschuetter** [comment]
Significant changes have been made in 2.1.0 to improve multi-platform support.

Please try to verify the steps outlined in the new website:
https://kohlschutter.github.io/junixsocket/customarch.html

Thanks for reporting!

**Comment by kohlschuetter** [comment]
junixsocket 2.2 now includes cross-compiled binaries for both Linux ARM 32-bit and 64-bit.

Please upgrade your dependencies to junixsocket 2.2.0 and try again

**Comment by nikoshet** [comment]
Sorry for the late response. Works perfectly now, thanks!
