### ISSUE TITLE
Exceptions "Not open" when update the library version from 2.0.4 to 2.3.0

### ISSUE THREAD

**Issue by vincenzopalazzo** [kohlschutter/junixsocket#75]
Hi.

I'm using this library for creating a wrapper for [c-lightning](https://github.com/ElementsProject/lightning) node.

In the actual version of the wrapper, I'm using version 2.0.4 and don't I have the problem but if I update the library to version 2.3.0 I have an exception with the message "Not open", like this:

```
jrpc.exceptions.ServiceException: Exception generated to doCall method of the class CLightningSocket with message
Not open
	at jrpc.service.socket.UnixDomainSocketRpc.doCall(UnixDomainSocketRpc.java:77)
	at jrpc.clightning.commands.AbstractRPCCommand.doRPCCommand(AbstractRPCCommand.java:48)
	at jrpc.clightning.commands.CommandRPCMediator.runCommand(CommandRPCMediator.java:86)
	at jrpc.clightning.CLightningRPC.decodePay(CLightningRPC.java:525)
	at jrpc.clightning.CLightningRPC.decodePay(CLightningRPC.java:505)
	at jrpc.clightning.TestCLightningRPC.testCommandDecodePayOne(TestCLightningRPC.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```
The method doCall() have this code

```
@Override
    public Object doCall(IWrapperSocketCall wrapperSocket, Type typeResult) throws ServiceException {
        if(socket.isClosed()){
            try {
                socket.connect(new AFUNIXSocketAddress(new File(pathSocket))); //this line trows the error.
            } catch (IOException e) {
                throw new ServiceException("Exception generated to doCall method of the class " + this.getClass().getSimpleName()
                        + " with message\n" + e.getLocalizedMessage());
            }
        }
        String serializationForm = converterJson.serialization(wrapperSocket);
        try {
            this.outputStream.write(serializationForm.getBytes(ENCODING));
            this.outputStream.flush();
        } catch (IOException e) {
            throw new ServiceException("Exception generated to doCall method of the class " + this.getClass().getSimpleName()
                    + " with message\n" + e.getLocalizedMessage());
        }
        Object o = converterJson.deserialization(inputStream, typeResult);
        try {
            socket.close();
        } catch (IOException e) {
            throw new ServiceException("Exception generated to doCall method of the class " + this.getClass().getSimpleName()
                    + " with message\n" + e.getLocalizedMessage());
        }
        return o;
    }
```

I'm doing anything wrong?

**Comment by kohlschuetter** [comment]
Hi vincenzo,

You're trying to reuse a Socket after it has been closed. This is not allowed according to the Java Socket API.

From java.net.Socket:
Once a socket has been closed, it is not available for further networking use (i.e. can't be reconnected or rebound). A new socket needs to be created.

I'll make sure to fix the error message in a future version to make that clear.

To fix your issue: Can you perhaps just create a new socket before the crashing line?
`socket = AFUNIXSocket.newInstance();`

Best,
Christian

PS: When you create new exceptions in a catch-clause, it's good practice to add the caught exception as the initCause, so we can trace the exception back to its source.

**Comment by vincenzopalazzo** [comment]
Thanks for your rapid answer @kohlschuetter and thanks for your advice to improve the exception.

I have resolved the error with your code, but I have another question on the good practice to manage the socket; I will introduce an example:

If I run the RPC command, is a good practice closed the socket? or is it very expensive, create a new Socket for each RPC command?

Thanks.

**Comment by kohlschuetter** [comment]
I would keep the sockets open, but I would do some measurements to be sure.
When you re-connect before each request then that may also incur performance penalties on the other side (the server you're connecting to), apart from asking the system to create a new unix socket, file descriptor, etc.

**Comment by vincenzopalazzo** [comment]
Thanks @kohlschuetter
